#!/bin/bash

# Fungsi untuk mengirim log notifikasi melalui Telegram
function send_log(){
  CHATID=$(cat /etc/perlogin/id)
  KEY=$(cat /etc/perlogin/token)
  TIME="10"
  URL="https://api.telegram.org/bot$KEY/sendMessage"
  TEXT="
<code>────────────────────</code>
<b>⚠️ NOTIF $protocol MULTI LOGIN ⚠️</b>
<code>────────────────────</code>
<code>Username    : </code><code>$user</code>
<code>Limit Ip    : </code><code>$iplimit</code>
<code>────────────────────</code>
<code>$ip_list</code>
<code>────────────────────</code>
  "
  curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

# Fungsi untuk memeriksa dan menghapus pengguna vmess yang melebihi batas IP
function vmip(){
  echo -n > /var/log/xray/access.log
  echo -n > /tmp/ipvmess.txt
  sleep 440

  data=( $(ls /etc/kyt/limit/vmess/ip) )

  for user in "${data[@]}"; do
    iplimit=$(cat /etc/kyt/limit/vmess/ip/$user)
    ip_list=$(grep -w "$user" /var/log/xray/access.log | tail -n 500 | awk '{print $3}' | sed 's/tcp://g' | cut -d ":" -f 1 | sort | uniq)
    
    ip_count=0
    for ip in $ip_list; do
      if grep -qw "$ip" /var/log/xray/access.log; then
        ip_count=$((ip_count + 1))
      fi
    done

    if [[ $ip_count -gt $iplimit ]]; then
      exp=$(grep -w "^### $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
      sed -i "/^### $user $exp/,/^},{/d" /etc/xray/config.json
      sed -i "/^### $user $exp/d" /etc/vmess/.vmess.db
      systemctl restart xray > /dev/null 2>&1
      rm -rf /etc/kyt/limit/vmess/ip/$user
      protocol="VMESS"
      send_log
    else
      echo "User $user tidak melebihi batas IP."
    fi

    sleep 0.1
  done
}

# Fungsi untuk memeriksa dan menghapus pengguna vless yang melebihi batas IP
function vlip(){
  echo -n > /var/log/xray/access.log
  echo -n > /tmp/ipvless.txt
  sleep 440

  data=( $(ls /etc/kyt/limit/vless/ip) )

  for user in "${data[@]}"; do
    iplimit=$(cat /etc/kyt/limit/vless/ip/$user)
    ip_list=$(grep -w "$user" /var/log/xray/access.log | tail -n 500 | awk '{print $3}' | sed 's/tcp://g' | cut -d ":" -f 1 | sort | uniq)
    
    ip_count=0
    for ip in $ip_list; do
      if grep -qw "$ip" /var/log/xray/access.log; then
        ip_count=$((ip_count + 1))
      fi
    done

    if [[ $ip_count -gt $iplimit ]]; then
      exp=$(grep -w "^### $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
      sed -i "/^### $user $exp/,/^},{/d" /etc/xray/config.json
      sed -i "/^### $user $exp/d" /etc/vless/.vless.db
      systemctl restart xray > /dev/null 2>&1
      rm -rf /etc/kyt/limit/vless/ip/$user
      protocol="VLESS"
      send_log
    else
      echo "User $user tidak melebihi batas IP."
    fi

    sleep 0.1
  done
}

# Fungsi untuk memeriksa dan menghapus pengguna trojan yang melebihi batas IP
function trip(){
  echo -n > /var/log/xray/access.log
  echo -n > /tmp/iptrojan.txt
  sleep 440

  data=( $(ls /etc/kyt/limit/trojan/ip) )

  for user in "${data[@]}"; do
    iplimit=$(cat /etc/kyt/limit/trojan/ip/$user)
    ip_list=$(grep -w "$user" /var/log/xray/access.log | tail -n 500 | awk '{print $3}' | sed 's/tcp://g' | cut -d ":" -f 1 | sort | uniq)
    
    ip_count=0
    for ip in $ip_list; do
      if grep -qw "$ip" /var/log/xray/access.log; then
        ip_count=$((ip_count + 1))
      fi
    done

    if [[ $ip_count -gt $iplimit ]]; then
      exp=$(grep -w "^### $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
      sed -i "/^### $user $exp/,/^},{/d" /etc/xray/config.json
      sed -i "/^### $user $exp/d" /etc/trojan/.trojan.db
      systemctl restart xray > /dev/null 2>&1
      rm -rf /etc/kyt/limit/trojan/ip/$user
      protocol="TROJAN"
      send_log
    else
      echo "User $user tidak melebihi batas IP."
    fi

    sleep 0.1
  done
}

# Menjalankan fungsi berdasarkan argumen yang diberikan
if [[ ${1} == "vmip" ]]; then
  vmip
elif [[ ${1} == "vlip" ]]; then
  vlip
elif [[ ${1} == "trip" ]]; then
  trip
fi

